### ISSUE TITLE
LiveSelect field should get initial values

### ISSUE THREAD

**Issue by goblinJoel** [maxmarcon/live_select#10]
I would like to be able to restore selections that hadn't been submitted yet, or that encountered an error on submission, like other forms seem to do via their changesets.

For example, I have a tabbed interface where switching tabs switches what info and form you're looking at. This live select is the only one that loses your work if you click away (within the same liveview) without saving.

It may be possible to simply take the current value from the form data using [Phoenix.HTML.Form.input_value/2](https://hexdocs.pm/phoenix_html/2.14.2/Phoenix.HTML.Form.html?#input_value/2) in the template.

**Comment by maxmarcon** [comment]
Hi @goblinJoel 

this should work on master now. If you have time and want to test it, that'd be really cool!

In order for live_select to pick the selected option(s) from the form, you'll have to pass the set of initially available options using the `options` assign:

```elixir
<%= live_select form, :field, mode: :tags, options: ["A", "B", "C"] %>
```

Now if the field in the form has value `["B", "C"]`, then B and C will be selected initially.

**Comment by maxmarcon** [comment]
closed with #8c9b2a0a8a3326086eda89a06fc83da3651a3e6e

**Comment by goblinJoel** [comment]
Messed with this on main some on Friday, but didn't get it all the way working because my use-case is goofy and doesn't use changesets the normal way due to a thru-table situation. But yesterday, I was able to confirm this works for me on the latest release. Thank you!

**Comment by sevab** [comment]
@maxmarcon looks like the code in https://github.com/maxmarcon/live_select/commit/8c9b2a0a8a3326086eda89a06fc83da3651a3e6e has been changed, and there's no longer way to set an initial value that will then be overridden by user's selection.

Do you have any tips for an idiomatic approach to this problem?
This is a typical use case where opening a form you would expect each input to have the exiting value already selected.

E.g. This obviously doesn't work anymore:
```elixir
      <.live_select
        label="Nationality"
        value={@person.nationality_id}
        field={@form[:nationality_search]}
        options={[{"None", nil} | Cb.Countries.options_for_select]} />
```

**Comment by maxmarcon** [comment]
Yes, the `value` is meant to override what is in the form.

The solution is to set the default value in the form :)

**Comment by sevab** [comment]
Thanks!

I'm creating the `form` from an ecto schema changeset of a db record. Basic Phoenix LiveView crud form basically:

```elixir
# person.ex
schema "people" do
  belongs_to(:nationality, Cb.Countries.Country, foreign_key: :nationality_id)
end

# person_live_form.ex:
def update(%{person: person} = assigns, socket) do
  {:ok, assign(socket, form: to_form(People.change_person(person)))}
end
```

I can certainly add a virtual field to the schema, in order to keep track of the `live_select's` value:
```elixir
schema "people" do
  belongs_to(:nationality, Cb.Countries.Country, foreign_key: :nationality_id)

  field(:nationality_search, :integer, virtual: true)
end

# then in liveview:
def update(%{person: person} = assigns, socket) do
  changeset = People.change_person(person, %{nationality_search: person.nationality_id})
  {:ok, assign(socket, form: to_form(changeset))}
end
```

But this seems to be a poor choice to me, poluting db schema definition with virtual fields for front-end components.

If there was a way to modify the form struct, it would be nice as it wouldn't require to modify the underlying schema, e.g.:
```elixir
def update(%{person: person} = assigns, socket) do
  form = to_form(People.change_person(person))
  form = Map.put(form, :nationality_search, person.nationality_id)
  {:ok, assign(socket, form: form)}
end
```

Though the above obviously doesn't work, as `form` is not a map, and I couldn't find any docs in `phoenix_html` to modifying the `Phoenix.HTML.Form` struct, but thought you might know.

This seems like a common scenario users of the package would need to handle, so if anybody has simple solutions, please share.

**Comment by maxmarcon** [comment]
> I can certainly add a virtual field to the schema, in order to keep track of the live_select's value:

why do you need that? live_select could be used to enter `nationality_id` directly. No need for a virtual field.

**Comment by sevab** [comment]
@maxmarcon ah, I misunderstood the docs 😅 I thought `live_select` maintains the value in a separate field named `"#{field_name}_search"` for it to work. All works now, thank you so much!

**Comment by maxmarcon** [comment]
You're welcome! No the actual field that will be selected is the one you pass with the `field` assign. But live_select does keep an extra field called `#{field_name}_text_input` to store the value of the text input box. You can ignore that one.
