### ISSUE TITLE
Limit component height attribute

### ISSUE THREAD

**Issue by gtaranti** [maxmarcon/live_select#14]
Is it possible to have an attribute in the component to limit the number of displayed results if there are too many?

i.e. like the 'limit' attribute
```
 <%= live_select(f, :selected_countries,
                  mode: :tags,
                  placeholder: "Type to select countries",
                  limit:  10
                )
%>
```

Because one of the issues, except the aesthetic one is that the layout of the page is distorted if the selection list gets too big, by adding vertical scrollbars.

**Comment by maxmarcon** [comment]
Hi @gtaranti.

You have complete control on the list of options displayed by the component. So you can:

```elixir
def handle_info(%LiveSelect.ChangeMsg{text: text, id: id}, socket) do
 # let's show only the first 10 matching options
  options = search(text) |> Enum.take(10)

  send_update(LiveSelect.Component, id: id, options: options)

 {:noreply, socket}
end
```

Let me know if this solution works for you

**Comment by gtaranti** [comment]
Ok, thanks.
I didn't think of that.
You're right...
