### ISSUE TITLE
extending use case with slots.

### ISSUE THREAD

**Issue by TwistingTwists** [maxmarcon/live_select#23]
![image](https://user-images.githubusercontent.com/11463027/228135295-a292988e-f935-4a6c-bc1d-bb7046ea5d10.png)

This is a sample image  / modal / dropdown that I want to display with live_select. 

 live_select has lots of 'keyboard' bindings and small things done right! I wish to support live_select with slots so that a custom slot can be passed for options / dropdown.
 
Would love you know your thoughts on this @maxmarcon .

**Comment by maxmarcon** [comment]
So you would like to display that huge UI as an option in the dropdown? :) 

Live select [already supports slots](https://hexdocs.pm/live_select/LiveSelect.html#module-slots), I'm sure you have noticed.

I guess what you want to do is possible in principle: you make sure that your `live_select_change` returns one entry, and you populate the content of the `:option` slot depending on the entry. It might work, but maybe it will require some styling work to make it look decent

**Comment by TwistingTwists** [comment]
Oh. So, few options might need to be styled differently! 

That makes sense. Thanks for the heads up!
