### ISSUE TITLE
preloading selected values from db

### ISSUE THREAD

**Issue by cadebward** [maxmarcon/live_select#27]
Hello there!

We've been using your library lately and firstly we must say: THANK YOU! This is a hard problem and we were so glad to not start from scratch.

I wanted to run past you a little problem we're having to see what you think. 

We are using live select in tags mode and using a list of genres that are stored in a separate database table. To start, we search the db for the first 10 genres alphabetically. Imagine a list of genres like Active, Adventure, Animation, etc. If I had previously selected something _outside of the first 10 results_, like the "War" genre, it will display the db id instead of the label. This happens because the options we passed to live select did not include "War", so when it attempted to find the value and retrieve the label, it was not found.

This list of options could potentially balloon to a huge list. We wouldn't want to pass _all_ options to the live select component because a) we don't know how large this data set is and b) we don't want the popup list to be a massive list of options that goes off the screen.

Thoughts?

**Comment by cadebward** [comment]
Thanks for the prompt response! That's very similar to what we ended up doing and it works pretty well. The edge case that doesn't work is when a new item is added to the list. Keep in mind, we're in tags mode so we have a list of elements selected. Here's the flow of things:

1. focus the input and load the first 10 items into the component
2. search for an element lower down the list, like `War`
3. select that element
4. validate is fired off, so we'll use that validate to grab the last item in the list and append it to the options so the component knows how to render the label
5. profit

The problem is: validate runs on update and breaks the assumption that the last item in params in a newly added item, and enters a render loop. This line is the culprit: https://github.com/maxmarcon/live_select/blob/main/lib/live_select/component.ex#L141. Do you recall why this was added to the update? It appears to function correctly without it.

**Comment by cadebward** [comment]
My apologies, as I was changing code all over the place, I left in the `value` override, which was causing us to hit into that line which I linked above. Leaving `value` untouched means we're not running validate on `update`, which means my approach explained above does work as expected. 

Nothing to see here folk! 😄

**Comment by maxmarcon** [comment]
Glad you were able to solve the issue! If you have any suggestions on how things could be improved so that other folks can avoid similar difficulties, let me know.
