### ISSUE TITLE
Multi-select support

### ISSUE THREAD

**Issue by saleyn** [maxmarcon/live_select#3]
It would be great if the support for multiple selected items is added.  When enabled, the input field would display either `N items selected` if more than 1 is selected, or work like it does now, and the selected items would have a checkbox next to them that would change state on click.

Maybe some ideas could be taken from:
- [slim select](https://slimselectjs.com)
- [dropdown with a search](https://flowbite.com/docs/components/dropdowns/#dropdown-with-search)

**Comment by maxmarcon** [comment]
Hi @saleyn . It's the very next thing on my TODO list (only in my mind so far, but I just added it to the README).

I very much prefer the style that uses tags like in your first link (slim select) and I think I will implement that one.

**Comment by saleyn** [comment]
That's great!  The only issue I envision with the slim select is when the tags don't fit in the initial space of the control. In that case slim select resizes the container, and in some cases that is not appropriate, and it would be better to display "N items selected".  The ability to search for items, like in the "Dropdown with search" in the second link would also be pretty useful.

Awaiting for your implementation of this new feature!

**Comment by maxmarcon** [comment]
> The only issue I envision with the slim select is when the tags don't fit in the initial space of the control. In that case slim select resizes the container, and in some cases that is not appropriate, and it would be better to display "N items selected"

Good point.

> The ability to search for items, like in the "Dropdown with search" in the second link would also be pretty useful.

You can already search for items by reacting to changes in the text input as shown [here](https://hexdocs.pm/live_select/LiveSelect.html#module-reacting-to-user-s-input). Or maybe you mean something else?

**Comment by saleyn** [comment]
> > The ability to search for items, like in the "Dropdown with search" in the second link would also be pretty useful.
> 
> You can already search for items by reacting to changes in the text input as shown [here](https://hexdocs.pm/live_select/LiveSelect.html#module-reacting-to-user-s-input). Or maybe you mean something else?

You are right, please disregard this point.

**Comment by maxmarcon** [comment]
Implemented! Check it out :)

**Comment by saleyn** [comment]
Great! Is there a way to limit the max number of selected tags?  [SlimSelect](https://slimselectjs.com/) recently implemented a similar feature, and what I like about that component is that when the tags are added they don't displace the selection component.

**Comment by maxmarcon** [comment]
> Great! Is there a way to limit the max number of selected tags?

there is none but you're welcome to create a PR for it if you want to :)

**Comment by maxmarcon** [comment]
> Great! Is there a way to limit the max number of selected tags?

Hi @saleyn. FYI, I added this feature. There is now an option called `max_selectable` that you can pass. Not released yet but available in the `main` branch. Thanks!
