### ISSUE TITLE
no case clause matching after upgrading to v1.0.4

### ISSUE THREAD

**Issue by carlotm** [maxmarcon/live_select#31]
I upgraded to live_select 1.0.4 and LV 0.19 and suddenly many tests are failing for me.
I think this is related to live_select but I could be very much wrong (don't see live_select files in the stacktrace...)

Maybe you have an idea.

Here's one of the failing tests:

```elixir
test "Adds an url", %{conn: conn, workshop: workshop} do
  {:ok, view, _} = live(conn, "/admin/workshops/#{workshop.id}/edit")

  x =
    view
    |> element("[phx-click='add-url']")
    |> render_click()
    |> assert_html("#workshop_urls_2_url", name: "workshop[urls][2][url]")
end
```

Here's the stacktrace, please note the error message is involving a live_select element:

```
  1) test Adds an url (ZdbWeb.Live.Workshops.UpdateTest)
     test/zdb_web/live/workshops/update_test.exs:198
     ** (EXIT from #PID<0.1082.0>) an exception was raised:
         ** (CaseClauseError) no case clause matching: [["select", %{id: "workshop-hallmarks", input_event: true, mode: :tags, selection: [%{key: "Steel Computer", label: "Steel Computer", value: "077388da-33bc-4653-9dfc-89bf88de460f"}, %{key: "Practical Granite Shoes", label: "Practical Granite Shoes", value: "0227eed3-6a50-4b7d-8137-812293aeb8fc"}, %{key: "Cotton Pants", label: "Cotton Pants", value: "7eb1fdcd-a7d8-4976-b831-2acdd4f7ab67"}]}], ["select", %{id: "workshop-tags", input_event: true, mode: :tags, selection: [%{key: "Small Concrete Computer", label: "Small Concrete Computer", value: "13a73bdc-08e7-49fb-b8c1-113129408ccf"}, %{key: "Fantastic Wooden Shirt", label: "Fantastic Wooden Shirt", value: "70a48d13-880d-4f76-86b7-de7c3c423ac4"}]}]]
             (phoenix_live_view 0.19.1) lib/phoenix_live_view/test/dom.ex:234: Phoenix.LiveViewTest.DOM.find_component/5
             (phoenix_live_view 0.19.1) lib/phoenix_live_view/test/dom.ex:211: anonymous fn/4 in Phoenix.LiveViewTest.DOM.merge_diff/2
             (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
             (phoenix_live_view 0.19.1) lib/phoenix_live_view/test/dom.ex:210: Phoenix.LiveViewTest.DOM.merge_diff/2
             (phoenix_live_view 0.19.1) lib/phoenix_live_view/test/client_proxy.ex:732: Phoenix.LiveViewTest.ClientProxy.merge_rendered/3
             (phoenix_live_view 0.19.1) lib/phoenix_live_view/test/client_proxy.ex:828: Phoenix.LiveViewTest.ClientProxy.handle_reply/2
             (phoenix_live_view 0.19.1) lib/phoenix_live_view/test/client_proxy.ex:452: Phoenix.LiveViewTest.ClientProxy.handle_info/2
             (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
             (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
             (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by maxmarcon** [comment]
What is the `[phx-click='add-url']` element and what does it do when you click on it?

It's unclear to me what is failing in your test... It looks like something is searching for a "select" HTML element with some attributes that are the ones used by live_select (tags, selection) but others that aren't (input_event).

More importantly, the live select component is not rendered as a select HTML element so that match will always fail! How was it succeeding before updating to the latest release?

I need more information about the test and your application to help you here.

**Comment by carlotm** [comment]
> What is the `[phx-click='add-url']` element and what does it do when you click on it?

It's a button, when clicked it updates the form (a field which is unrelated to the live_select one).

```elixir
def handle_event("add-url", _, socket) do
  socket =
    update(socket, :form, fn %{source: changeset} ->
      urls =
        case Ecto.Changeset.fetch_field(changeset, :urls) do
          :error -> []
          {_, existing} -> existing
        end ++ [%{}]

      changeset
      |> Ecto.Changeset.put_embed(:urls, urls)
      |> to_form()
    end)

  {:noreply, socket}
end
```

> 
> It's unclear to me what is failing in your test... It looks like something is searching for a "select" HTML element with some attributes that are the ones used by live_select (tags, selection) but others that aren't (input_event).
> 
> More importantly, the live select component is not rendered as a select HTML element so that match will always fail! How was it succeeding before updating to the latest release?

The test is unrelated to the live_select component.
The exact line which is raising is `render_click()` (`render()` does not raise, but of course makes the test fail)

This could be related to LV rather than live_select, can I provide any other detail?

**Comment by maxmarcon** [comment]
> The test is unrelated to the live_select component.

I don't understand why you think it's related to live_select then

**Comment by carlotm** [comment]
Because I have many tests failing in the only live view that uses live_select and the stacktrace reads:

```elixir
** (CaseClauseError) no case clause matching: [["select", %{id: "workshop-hallmarks", input_event: true, mode: :tags, selection: [%{key: "Intelligent Pants", label: "Intelligent Pants", value: "eee92b18-b8f1-4d0d-a53d-1fc4462644e2"}, %{key: "Granite Table", label: "Granite Table", value: "5905f86b-6139-4d27-b9bf-41a55b0ff0bc"}, %{key: "Small Granite Shirt", label: "Small Granite Shirt", value: "d781bc33-112c-471e-a666-59ed4f821bd5"}]}], ["select", %{id: "workshop-tags", input_event: true, mode: :tags, selection: [%{key: "Practical Wooden Gloves", label: "Practical Wooden Gloves", value: "c55df120-077d-4e53-8ddb-535564fb3cdb"}, %{key: "Rubber Shirt", label: "Rubber Shirt", value: "484fe766-8984-4e12-9d17-73fee92c017e"}]}]]
```

**Comment by maxmarcon** [comment]
As I said, this line:

```
** (CaseClauseError) no case clause matching: [["select", %{id: "workshop-hallmarks", input_event: true, mode: :tags, selection: [%{key: "Intelligent Pants", label: "Intelligent Pants", value: "eee92b18-b8f1-4d0d-a53d-1fc4462644e2"}, %{key: "Granite Table", label: "Granite Table", value: "5905f86b-6139-4d27-b9bf-41a55b0ff0bc"}, %{key: "Small Granite Shirt", label: "Small Granite Shirt", value: "d781bc33-112c-471e-a666-59ed4f821bd5"}]}], ["select", %{id: "workshop-tags", input_event: true, mode: :tags, selection: [%{key: "Practical Wooden Gloves", label: "Practical Wooden Gloves", value: "c55df120-077d-4e53-8ddb-535564fb3cdb"}, %{key: "Rubber Shirt", label: "Rubber Shirt", value: "484fe766-8984-4e12-9d17-73fee92c017e"}]}]]
```

is looking for a select HTML input. That can't be in the live select component because the live select component doesn't contain _any_ HTML select elements :) 

So you need to figure out where this line is coming from. What is looking for a "select" input element with those attributes in your tests?

**Comment by carlotm** [comment]
> is looking for a select HTML input. That can't be in the live select component because the live select component doesn't contain _any_ HTML select elements :)

:+1: Thanks, sorry for the noise

**Comment by maxmarcon** [comment]
No worries. Were you able to find the root cause of the issue in the end?

**Comment by carlotm** [comment]
I was using a custom live component to wrap live_select (as a way to decouble the library...).
When I replaced the custom component with live_select directly, the problem disappeared.
