### ISSUE TITLE
this.el.querySelector(...) is null

### ISSUE THREAD

**Issue by carlotm** [maxmarcon/live_select#39]
Hi,

I am executing

```elixir
send_update(LiveSelect.Component, id: "workshop-tags", value: list_of_tags())
```

inside an `update/2` callback of a live component, the live select updates correctly, but I got a

```
Uncaught TypeError: this.el.querySelector(...) is null
```

message, and the offending line is https://github.com/maxmarcon/live_select/blob/30c9fab961e554c416aa5bbcf7bd7554f78d5cc1/assets/js/live_select.js#L82

This breaks my javascript script.

Am I doing something wrong?
Any idea how to solve?

Thank you

**Comment by maxmarcon** [comment]
Hi!

what's the reason for updating `value` and not `options` ?

**Comment by carlotm** [comment]
I want to programmatically set the value of live_select (it's an edit form).
I followed this https://hexdocs.pm/live_select/LiveSelect.html#module-controlling-the-selection-programmatically

Please note that the value is set correctly and I see the existing tags pre-selected.

**Comment by maxmarcon** [comment]
I see. Can you show me more code please? Like how you're rendering the component, and the function that sends the update. Thanks

**Comment by carlotm** [comment]
Ah!
In the live component that used live_select I had an hook which for whatever reason used `async mount` instead of `mount` (it had some `await` inside).

I converted the parent live component hook mount to `mount` and the awaits inside to `.then` and it now works like a charm!

Probably the parent live component wasn't really mounted when the live_select javascript did run, so `this.el` was undefined.

Sorry for the noise!
Thank you very much for this library!

**Comment by maxmarcon** [comment]
No worries! Glad you figured it out and thank you for using the library. Always ready to help.
