### ISSUE TITLE
Add css config for clear button

### ISSUE THREAD

**Issue by damir** [maxmarcon/live_select#40]
Hi Max,

There is no option to configure css class for clear button, it looks like this when switching to dark mode:

<img width="453" alt="Screenshot 2023-09-17 at 2 26 06 PM" src="https://github.com/maxmarcon/live_select/assets/7764/8efd39fa-e1e0-4337-98d0-e1245afe7b01">

**Comment by maxmarcon** [comment]
Hi @damir . Good point, there isn't an option for that atm!

I will add it as soon as I find some time.

In the meantime you can add a css rule as workaround. Something like this should work:

```
div[phx-hook=LiveSelect] button[phx-click=clear] {
   color: white
}
```

**Comment by maxmarcon** [comment]
Note to self with additional TODOs:

1. apply relative position to clear button's parent, so it is positioned correctly even with `style=none`
2. do not apply relative position to entire liveselect component when `style=tailwind`, as it's useless

**Comment by damir** [comment]
That works, thanks for the hint! I am using petal components and it looks like this:

``` css
html.dark div[phx-hook='LiveSelect'] button[phx-click='clear'] {
  @apply text-gray-500;
}
```

**Comment by maxmarcon** [comment]
added to release `1.2.0`.

The option is called: `clear_button_class`
