### ISSUE TITLE
Respect `:selected_option_class` when in `:single` mode

### ISSUE THREAD

**Issue by AHBruns** [maxmarcon/live_select#42]
Per the docs, the `:selected_option_class` attr is only available when in `:tags` mode. However, I believe being able to style the current selection uniquely is valuable even in `:single` mode.

This is in fact how chrome's built-in select works (notice the check next to `female`, indicating that is the current selection):

<img width="169" alt="Screenshot 2023-09-29 at 8 49 42 PM" src="https://github.com/maxmarcon/live_select/assets/33048856/ff0bf6fb-c87f-43fa-8279-1702ad2c7fb2">

If you're open to this change, I'd be happy to PR it. Just don't want work to go to waste.

**Comment by maxmarcon** [comment]
Hi @AHBruns and thanks for pointing this out. I agree with your observation, and I'd welcome a PR for this change!

Just be aware that I'll be traveling for the next couple of weeks with little time to spend for coding. So it might take a while before I can review your PR, but I'll do it as soon as I find some time!

Thanks

**Comment by AHBruns** [comment]
I'm up against a tight deadline at work this week, but I will have time next week. Planning to PR this then assuming it's fairly straightforward.

**Comment by maxmarcon** [comment]
This is no longer the case, the styles for the elements in the drop down work irrespective of the mode. The docs need to be updated
