### ISSUE TITLE
Dropdown menu should open when the input field is clicked, rather than focused

### ISSUE THREAD

**Issue by egeersoz** [maxmarcon/live_select#49]
Right now, in order to select multiple options from the dropdown menu, you need to:

1. Click the input element (which focuses it)
2. Select an option
3. Click off the field to blur it
4. Click on the field to re-focus it

This is not good UX. The dropdown menu should open when the input field receives a click event.

**Comment by maxmarcon** [comment]
Thanks for pointing this out.

Can you please test the latest main? The behavior should now be as you expect.
