### ISSUE TITLE
Have the option to populate a value for the input by default

### ISSUE THREAD

**Issue by silviurosu** [maxmarcon/live_select#52]
When displaying the search in a search result page where we landed by url I would like to be able to populate the value of the input using the parameters I have in url. I have not found any way to set a default value. There is the option to set a default vaule for the dropdown if the input is empty, but no way to have the input not empty
<img width="1129" alt="Screenshot 2023-12-24 at 20 00 14" src="https://github.com/maxmarcon/live_select/assets/509403/288f5f1f-b8ac-4b85-8f43-1c54acdf337f">
Is there a way I can populate the input value?

**Comment by maxmarcon** [comment]
Hi sorry for answering only now. Yes, the input is automatically populated from the values in the form. If you create a form where the field has the desired value, it will be used to populate the live select component.

**Comment by silviurosu** [comment]
Yeah that's true, I tried that but the problem I have is that the value is a simple string. The value I need in live_select is a map, with a value and label. The value displayed in the form is not the value I want to submit on the server side.

Also setting the value in the input will trigger def handle_event("update",...) which I do not want because will trigger again the search and redirect.

**Comment by maxmarcon** [comment]
You have to populate the initial options as well, so that they contain the entry with the label corresponding to the selected value, see here: https://github.com/maxmarcon/live_select/issues/27#issuecomment-1559947041

**Comment by silviurosu** [comment]
I was able to preselect the value using options and value params. Thanks for help
