### ISSUE TITLE
Is there a way to allow for filling without having the user click on the option?

### ISSUE THREAD

**Issue by Morzaram** [maxmarcon/live_select#57]
Hey there I was wondering if there's a way for the user to simply type in the option and move to the next tab without them having to select it. 

Apologies if it's obvious. 

Here's an example of what I'm talking about
![ScreenRecording2024-01-31at6 29 22PM-ezgif com-video-to-gif-converter](https://github.com/maxmarcon/live_select/assets/70202379/27d2c3d8-075f-403b-b8e2-95e395623f7c)

**Comment by maxmarcon** [comment]
Hi @Morzaram. If there is only one selectable option, hitting Enter will select it.

**Comment by Morzaram** [comment]
Thanks!
