### ISSUE TITLE
After sending a tag, while the input field is blank it considers the last value as current

### ISSUE THREAD

**Issue by renews** [maxmarcon/live_select#60]
While using the mode tag, after the user inserting anythin on the field and the tag being created, if you press enter on the blank field, it still considers as if the text is there and duplicate keep insert new tags every time you press enter.

**Comment by maxmarcon** [comment]
Hi @renews . I've never seen this behavior before, nor can I replicate it on the showcase app.

Where do you see it? Share a repo that reproduces it please

**Comment by renews** [comment]
Looks like if you have any processing happening liek in the showcase app, it works normally. I guess you can close this
