### ISSUE TITLE
resetting list of options when text input field becomes empty

### ISSUE THREAD

**Issue by hunterboerner** [maxmarcon/live_select#74]
When options are cleared I want to show the initial full selection list. However currently the `live_select_id` is not sent with the `options_clear` event so I cannot reset the live select form. My workaround is to store the last `live_select_id` and then clear that with the `options_clear` event but I'm not sure this will work if I have multiple live selects on the same page.

**Comment by maxmarcon** [comment]
Thanks, I understand the use case here. However, the `options_clear` event is internal to LiveSelect, and you would not be able to handle it in your live view/component. However, your description sounds like you are able to handle it. Can you please clarify how?

One idea would be to send the `options_clear` event also to the live view/component that renders LiveSelect, with the `id` as you suggest

**Comment by hunterboerner** [comment]
I actually don’t know how to make it work.  How can I reset the list of
options when the field is cleared? It doesnt send a live select event with
a blank text field

**Comment by maxmarcon** [comment]
Does [this cheatsheet](https://hexdocs.pm/live_select/cheatsheet.html#2-with-a-fixed-set-of-default-options-to-be-displayed-when-the-text-input-is-empty) work for you?

**Comment by maxmarcon** [comment]
It should work, I created it exactly to implement this use case
