### ISSUE TITLE
How to select entries and render form inputs from them

### ISSUE THREAD

**Issue by camfeghali** [maxmarcon/live_select#79]
This is more so a question as to if this is possible / if anyone has done something similar.

I have a `<.live_select>` component on `mode={:tags}`, and i want each selection that i make to hold 1 or more inputs linked to a parent form.

Ex:

```
      <.simple_form
        for={@form}
        id="draft_order-form"
        phx-target={@myself}
        phx-change="validate"
        phx-submit="save"
      >
        <.live_select
          value_mapper={&value_mapper/1}
          mode={:tags}
          placeholder="Search for a product"
          field={@form[:items]}
          update_min_len={0}
          phx-target={@myself}
          allow_clear
          container_extra_class="flex flex-col"
          dropdown_extra_class="top-11"
          tags_container_extra_class="order-last hidden"
          tag_extra_class="bg-green-200 m-1 p-2"
        >
        </.live_select>
                    <.inputs_for :let={item} field={@form[:items]}>
                          <.input type="number" field={item[:quantity]} min={0} max={25} />
                    </.inputs_for>
      </.simple_form>
```

Rendering the selections with inputs is going fine, but the input that is rendered is missing the "id" identifier, even though i'm passing it via the `value_mapper`

```
<input type="hidden" name="draft_order_creation_form[items][0][_persistent_id]" value="0">
```

I expect the name to end with [id] and not [_persistent_id]

Thoughts ? :)

**Comment by maxmarcon** [comment]
You need to share more code and explains better what you want to achieve, cause I didn't understand.

**Comment by maxmarcon** [comment]
thanks. 2 questions:

 - what exactly isn't working as expected?
 - can you please also show `value_mapper/1` ?

**Comment by camfeghali** [comment]
The main issue is that a id of items is not binded to the input field generated by `inputs_for`.
This is the generated markup:
```
<input type="hidden" name="draft_order_creation_form[items][0][_persistent_id]" value="0">
```
I expect it to be [id] and not [_persistent_id]. Because i pass in a id value to the `items` attr

Here's the code for that handles the select change and the value_mapper

```
        "draft_order_creation_form_items_search" ->
          Variants.in_market(country_code)
          |> Variants.select_image()
          |> Variants.search_by_product_name(text)
          |> select([v, vm, m, product: p, image: image], %{
            idid: v.id,
            variant_id: v.id,
            variant_name: v.name,
            market_id: m.id,
            market: m.country_code,
            price: vm.price,
            product: p,
            product_name: p.name,
            image: image
          })
          |> Repo.all()
          |> Enum.map(
            &%{
              name: &1.variant_name,
              image: Pdex.Catalog.Images.image_url(&1.image),
              variant_id: &1.variant_id,
              quantity: 1,
              product_name: &1.product_name,
              price: &1.price
            }
          )
          |> Enum.map(&value_mapper/1)
          
  def value_mapper(%{variant_id: variant_id} = record) do
    %{
      label: record.product_name <> " - " <> record.name,
      value: record
    }
  end
```

the fact that id is not passed to the markup makes it so that ecto cannot manage those assoc when casting

**Comment by maxmarcon** [comment]
```
<input type="hidden" name="draft_order_creation_form[items][0][_persistent_id]" value="0">
```

Who's rendering this input? Your markup in `<.inputs_for>` looks different:

```
                          <.input type="number" field={item[:quantity]} min={0} max={25} />
```

**Comment by camfeghali** [comment]
AFAIK, inputs_for generates that hidden input field

**Comment by maxmarcon** [comment]
Ok, this has nothing to do with LiveSelect? It's all happening outside of it.

It's an Ecto question. Why don't you ask the question on Elixirforum?

(that's a nice-looking form btw)

**Comment by camfeghali** [comment]
Thank you! I tried the forum already, the reason I came here was to see if someone had already used live_select like that. I noticed that the best option was to separate `items` and `items_search` in the form, and resolve selection/input change by merging/appending changes. 

Thanks for the discussion and your work!

**Comment by maxmarcon** [comment]
You're welcome. Unless I'm missing something (please let me know if I do) this problem is completely orthogonal to live_select. You mange the items yourself, and then render them in the form. If you remove live_select you'd still have the same problem.

**Comment by camfeghali** [comment]
It is when you separate `:items` and `:items_search`. But I thought I could set the field for live_select to be :items

```
        <.live_select
          mode={:tags}
          placeholder="Search for a product"
          field={@form[:items_search]}
          update_min_len={0}
          phx-target={@myself}
          allow_clear
          container_extra_class="flex flex-col"
          dropdown_extra_class="top-11"
          tags_container_extra_class="order-last hidden"
          tag_extra_class="bg-green-200 m-1 p-2"
        >
```

And streamline it. But yes I agree :)
