### ISSUE TITLE
[NOT ISSUE] - use without submit button

### ISSUE THREAD

**Issue by kuatroka** [maxmarcon/live_select#89]
New to Phoenix, so pls bear with me if trivial. 

Does this lib can do the autocomplete/typeahead without the need to click on the SUBMIT button? Is it as easy as just changing `phx-sumbit` to `phx-change` or something else needs to be done. Thanks.

**Comment by maxmarcon** [comment]
You have to implement a handler for the `live_select_change` event as explained in [the readme](https://hexdocs.pm/live_select/readme.html#content) and  the [examples](https://hexdocs.pm/live_select/LiveSelect.html#module-examples)

**Comment by kuatroka** [comment]
Thanks
